#!/bin/bash

JOBW_TMP_FILE=$1
JOBW_JOB_PPID=$2

while true; do
    if [ -a "$JOBW_TMP_FILE.started" ]; then
        break;
    fi
    sleep 0.05
done

ps -o ppid,pid | grep "^"$JOBW_JOB_PPID | awk '{ print $2 }' | sort -u > $JOBW_TMP_FILE.sub2

comm -13 $JOBW_TMP_FILE.sub1 $JOBW_TMP_FILE.sub2 > $JOBW_TMP_FILE.pid


