#!/usr/bin/env bash


if [ -z "${TARGET_NUM_STAGED_FILES}" ]; then
    TARGET_NUM_STAGED_FILES=2048
fi
if [ -z "${FILLING_NUM_STAGED_FILES}" ]; then
    FILLING_NUM_STAGED_FILES=1024
fi
if [ -z "${MINIMUM_NUM_STAGED_FILES}" ]; then
    MINIMUM_NUM_STAGED_FILES=512
fi
if [ -z "${STAGE_SHUF_NUM}" ]; then
    STAGE_SHUF_NUM=32
fi


BLACK='\033[0;30m'
DGRAY='\033[1;30m'
RED='\033[0;31m'
LRED='\033[1;31m'
GREEN='\033[0;32m'
LGREEN='\033[1;32m'
BROWN='\033[0;33m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
LBLUE='\033[1;34m'
PURPLE='\033[0;35m'
LPURPLE='\033[1;35m'
CYAN='\033[0;36m'
LCYAN='\033[1;36m'
LGRAY='\033[0;37m'
WHITE='\033[1;37m'
NC='\033[0m' # No Color


# NOTE: 
# when using trap "" 2 , ^C will NOT interrupt the current command as nothing need to happen
# when using trap "function_name" 2, ^C will interrupt the current running command, as it has to interrupt it and run the specified function. 

function force_int() {
    echo
    echo -e "...... [ ${DGRAY}"`date`"${NC} ] ...... [ ${RED}Force killing${NC} ]"
    kill -9 $JOBC_JOB_PID > /dev/null 2>&1
    trap "" 2
}

function safe_int() {
    trap "" 2
    echo
    echo -e "...... [ ${DGRAY}"`date`"${NC} ] ...... [ ${LRED}Try to interrupt${NC} ]"
    echo -e "...... [ ${LRED}To force killing, press ${WHITE}^C${LRED} again. ${NC} ]"
    kill -2 $JOBC_JOB_PID > /dev/null 2>&1
    trap "force_int" 2
}

function request_to_end() {
    trap "" 2
    touch "$PROC_PREFIX.REQUEST_TO_END"
    echo
    echo -e "...... [ ${DGRAY}"`date`"${NC} ] ...... [ ${LPURPLE}User request to end${NC} ]"
}

function request_to_end_during_running() {
    trap "" 2
    request_to_end
    echo -e "...... [ ${LPURPLE}To interrupt the current process, press ${WHITE}^C${LPURPLE} again. ${NC} ]"
    trap "safe_int" 2
}

function safe_exit() {
    trap "" 2
    touch "$PROC_PREFIX.INTERRUPTED"
    echo
    echo -e "...... [ ${DGRAY}"`date`"${NC} ] ...... [ ${PURPLE}Ended by the user${NC} ]"
    exit 0
}


function stage_more_files() {
    num_to_stage=$((${TARGET_NUM_STAGED_FILES} - ${num_staged}))
    if [[ "$num_to_stage" -gt 0 ]]; then
        # echo -e "...... [ ${BROWN}"STAGE"${NC} ] ...... [ ${LPURPLE}${num_to_stage}${NC} files ]" >&2
        ( cd "$JOBC_VAR_DIR/q" || exit -1 ; ( ls -U | sort | head -n"${num_to_stage}" | xargs -I '{}' mv '{}' "$JOBC_VAR_DIR/qs" 2>/dev/null ) )
    fi
}


function get_one_task_filename() {
    staged_filenames=($(ls -U "$JOBC_VAR_DIR/qs"))
    num_staged="${#staged_filenames[@]}"
    if [[ "${num_staged}" -eq 0 ]]; then
        stage_more_files
        staged_filenames=($(ls -U "$JOBC_VAR_DIR/qs"))
    elif [[ "${num_staged}" -le "$MINIMUM_NUM_STAGED_FILES" || "${num_staged}" -eq "$FILLING_NUM_STAGED_FILES" ]]; then
        stage_more_files
    fi

    printf '%s\n' "${staged_filenames[@]}" | sed '/^$/d' | sort | head -n"${STAGE_SHUF_NUM}" | shuf | head -n1
}

# main

pushd `dirname $0` > /dev/null ; SCRIPT_DIR="`pwd`"; popd > /dev/null

if [ "$1" == "" ]; then
    echo "JOB-CLIENT WACTHER" >&2
    echo "  "`basename "$0"`" JOBC_VAR_DIR [JOBCW_ID [PROC_DIR]]" >&2
    exit 1
fi

JOBC_VAR_DIR="$1"
mkdir -p "${JOBC_VAR_DIR}"

CURRENT_DIR=$(pwd)
cd "$JOBC_VAR_DIR" || exit -1
JOBC_VAR_DIR=$(pwd -P)
cd "${CURRENT_DIR}"

JOBCW_ID="$2"
if [ "$JOBCW_ID" == "" ]; then
    JOBCW_ID="unknown"
fi

PROC_DIR="$3"
if [ "$PROC_DIR" == "" ]; then
    PROC_DIR="$JOBC_VAR_DIR/proc"
fi

mkdir -p "$JOBC_VAR_DIR/q"  # queueing
mkdir -p "$JOBC_VAR_DIR/qs"  # the short list for tasks going to be executed
mkdir -p "$JOBC_VAR_DIR/r"  # running
mkdir -p "$JOBC_VAR_DIR/d"  # done
mkdir -p "$JOBC_VAR_DIR/c"  # canceled

EHTER_UUID=`ifconfig | grep ether | sha1sum | awk '{print $1}'`
if [ "$(uname)" == "Darwin" ]; then
    HD_UUID="mac_hd"
else
    HD_UUID=`blkid | grep -oP 'UUID="\K[^"]+' | sha1sum | awk '{print $1}'`
fi
HOSTNAME=`hostname`

mkdir -p "$PROC_DIR"
PROC_PREFIX="$PROC_DIR"/${HOSTNAME}.${EHTER_UUID}.${HD_UUID}.$$

rm -f "$PROC_PREFIX.REQUEST_TO_END"
rm -f "$PROC_PREFIX.INTERRUPTED"
rm -f "$JOBC_VAR_DIR/DONE"

trap 'safe_exit' 2

while true; do
    JOBCW_QUIT_ON_EMPTY=0
    if [ -f "$JOBC_VAR_DIR/quit_on_empty" ]; then
        JOBCW_QUIT_ON_EMPTY=1
    fi
    if [ -f "$JOBC_VAR_DIR/quit" ]; then
        trap "" 2
        echo -e "...... [ ${DGRAY}"`date`"${NC} ] ...... [ ${PURPLE}Ended per 'quit' tag ${NC} ]"
        break;
    fi
   
    rm -f "${PROC_PREFIX}.JOBCW_QUEUE_NONEMPTY"

    echo -e "...... [ ${LBLUE}DIR PATH${NC} ] $JOBC_VAR_DIR"
    echo -e "...... [ ${DGRAY}"`date`"${NC} ] ...... [ ${CYAN}List${NC} ]"
    # ls -tr $JOBC_VAR_DIR/q | head -n1 | while read line ; do
    # use unordered ls to speed up, and shuf to reduce race condition

    get_one_task_filename | while read line ; do

        # the code in the block actually run only for one iteration

        if [ -f "$PROC_PREFIX.REQUEST_TO_END" ]; then
            safe_exit;
        fi

        touch "${PROC_PREFIX}.JOBCW_QUEUE_NONEMPTY"

        JOB_FOLDER_Q="$JOBC_VAR_DIR/qs/$line"
        JOB_FOLDER_R="$JOBC_VAR_DIR/r/$line"
        #JOB_FOLDER_D="$JOBC_VAR_DIR/d/$line"

        echo -e "...... [ ${LBLUE}DIR PATH${NC} ] $JOBC_VAR_DIR"
        echo -e "...... [ ${DGRAY}"`date`"${NC} ] ...... [ ${YELLOW}Run${NC} ]"
        echo -e "[ $JOB_FOLDER_Q ]"
        mv "$JOB_FOLDER_Q" "$JOBC_VAR_DIR/r"
        if [ "$?" != "0" ]; then
            echo -e "...... [ ${DGRAY}"`date`"${NC} ] ...... [ ${LCYAN}Taken by another worker${NC} ]"
            contiue;
        fi

        trap "request_to_end_during_running" 2

        bash "$JOB_FOLDER_R" & JOBC_JOB_PID=`echo $!`
        
        ( echo -e "[ "`date`" ] [ "$JOBCW_ID" ]"$'\n'"  START:  $line" ; \
            ( $SCRIPT_DIR/session_info | sed -e 's/^/\t/' ) ) >> $JOBC_VAR_DIR/log
        wait $JOBC_JOB_PID
        wait $JOBC_JOB_PID  # if safe int happened
        wait $JOBC_JOB_PID  # if force killing happened
        wait $JOBC_JOB_PID
        JOBC_JOB_EC=$?
        
        trap "request_to_end" 2
        
        if [ "$JOBC_JOB_EC" -eq "0" ]; then
            mv "$JOB_FOLDER_R" "$JOBC_VAR_DIR/d"
            ( echo "[ "`date`" ] [ "$JOBCW_ID" ]"$'\n'"  DONE:   $line" ; \
                ( $SCRIPT_DIR/session_info | sed -e 's/^/    /' ) ) >> $JOBC_VAR_DIR/log
            echo -e "...... [ ${DGRAY}"`date`"${NC} ] ...... [ ${LGREEN}Done${NC} ]"
        else
            mv "$JOB_FOLDER_R" "$JOBC_VAR_DIR/c"
            ( echo -e "[ "`date`" ] [ "$JOBCW_ID" ]"$'\n'"  CANCEL: $line" ; \
                ( $SCRIPT_DIR/session_info | sed -e 's/^/    /' ) ) >> $JOBC_VAR_DIR/log
            echo -e "...... [ ${DGRAY}"`date`"${NC} ] ...... [ ${LRED}Interrupted${NC} ]"
        fi

    done
    
    if [ -f "$PROC_PREFIX.REQUEST_TO_END" ]; then
        safe_exit
    fi

    trap 'safe_exit' 2

    if [ ! -f "${PROC_PREFIX}.JOBCW_QUEUE_NONEMPTY" ]; then
        echo -e "...... [ ${LBLUE}DIR PATH${NC} ] $JOBC_VAR_DIR"
        if [ "$JOBCW_QUIT_ON_EMPTY" -ne "0" ]; then
            echo -e "...... [ ${DGRAY}"`date`"${NC} ] ...... [ ${PURPLE}Ended due to an empty queue${NC} ]"
            break;
        fi
        SLEEP_TIME=$(($RANDOM % 10 + 5))
        echo -e "...... [ ${DGRAY}"`date`"${NC} ] ...... [ ${BROWN}Sleep for ${SLEEP_TIME}s${NC} ]"
        sleep ${SLEEP_TIME}
    fi

done

touch $JOBC_VAR_DIR/DONE

exit 0

