#!/usr/bin/env python3
import argparse
import os
import sys

TOOLBOX_DIR = os.path.dirname(os.path.abspath(__file__))


def main():
    parser = argparse.ArgumentParser(description="jobc server command line")
    parser.add_argument("--root-dir", type=str, default=None, help="root dir")
    parser.add_subparsers(title="mode", dest="mode", description="command line mode")

    args = parser.parse_args()

    root_dir = args.root_dir
    if not root_dir:
        if "JOBC_ROOT" in os.environ:
            root_dir = os.environ["JOBC_ROOT"]
    assert root_dir, "either set env variable JOBC_ROOT or specify --root-dir"

    etc_dir = os.path.join(root_dir, "etc")
    var_dir = os.path.join(root_dir, "var")


if __name__ == "__main__":
    main()
