#!/bin/bash

if [ "$1" == "" ]; then
    echo "JOB-CLIENT WAIT"
    echo "  "`basename "$0"`" (stdin as input)" >&2
    echo "  "`basename "$0"`" LIST_FILE_FOR_JOBC_VAR_DIR" >&2
    exit 1
fi

JOBC_DIR_LIST="$1"
if [ "$JOBC_DIR_LIST" == "" ]; then
    JOBC_DIR_LIST="-"
fi

cat $JOBC_DIR_LIST | while read line; do
    if [ "$line" == "" ]; then
        continue;
    fi
    echo $line
    while [ ! -f $line/DONE ]; do
        sleep 2
    done
done

