#!/bin/bash

# functions

function show_help() {
  echon='printf %s'
  echo
  echo        "JOBW: A simple job watcher for logging and emailing job outputs and status"
  echo        "Written by Yuting Zhang ( http://www.ytzhang.net/ )"
  echo
  echo        "USAGE: `basename $0` [opts] cmd [cmd_args]"
  echo
  echo        "ARGS:"
  echo
  echo        "  -a email_addr     send email to email_addr [JOBW_EMAIL=email_addr]"
  if [ ! -z "$JOBW_EMAIL" ]; then
    echo      "                      default value:" "$JOBW_EMAIL"
  fi
  $echon      "  -u                do not send email [unset JOBW_EMAIL]"
  if [ -z "$JOBW_EMAIL" ]; then echo " (default)"
  else echo; fi
  echo
  $echon      "  -Y                attach log in email [JOBW_LOG_IN_EMAIL=1]"
  if [ "$JOBW_LOG_IN_EMAIL" -gt "0" ]; then echo " (default)"
  else echo; fi
  $echon      "  -N                do not attach log in email [JOBW_LOG_IN_EMAIL=0]"
  if [ "$JOBW_LOG_IN_EMAIL" -gt "0" ]; then echo
  else echo " (default)"; fi
  echo
  echo        "  -s job_subject    job subject [JOBW_SUBJECT=job_subject]"
  echo        "                      default value:" "$JOBW_SUBJECT"
  echo
  echo        "  -o log_file       log to log_file [JOBW_LOG_FILE=log_file]"
  if [ ! -z "$JOBW_LOG_FILE" ]; then
    echo      "                      default value:" "$JOBW_LOG_FILE"
  fi
  $echon      "  -n                do not write log to a file [unset JOB_LOG_FILE]"
  if [ -z "$JOBW_LOG_FILE" ]; then echo " (default)"
  else echo; fi
  echo
  echo        "  -w                overwrite the log file instead of appending"
  echo        "                      remark: without this option new log will be appended"
  echo
  echo        "  -f                log full output [JOBW_LOG_BYTE=inf]"
  echo        "  -b num_block      head and tail the log output by 512*num_block bytes"
  echo        "                      [JOBW_LOG_BYTE=num_block*512]"
  echo        "  -c num_char       head and tail the log output by num_char bytes"
  echo        "                      [JOBW_LOG_BYTE=num_char]"
  echo        "                      default value:" $JOBW_LOG_BYTE
  echo
  echo        "  -l lines_in_abs   lines in abstract [JOBW_LINES=lines_in_abs]"
  echo        "                      default value:" $JOBW_LINES
  echo
  echo        "  -m string         attach more message in the log and email"
  echo
  echo        "  -I                make the gard process interruptible by Ctrl+C"
  $echon      "                      [JOBW_INTERRUPTIBLE=1]"
  if [ "$JOBW_LOG_IN_EMAIL" -gt "0" ]; then echo
  else echo " (default)"; fi
  echo        "  -i                make the gard process uninterruptible by Ctrl+C"
  $echon      "                      [JOBW_INTERRUPTIBLE=0]"
  if [ "$JOBW_LOG_IN_EMAIL" -gt "0" ]; then echo " (default)"
  else echo; fi
  echo
  echo        "  -v                show version"
  echo        "  -d                disable interative command line"
  echo        "  -h                show this help"
  echo
}


function finish() {

trap "" 2

wait $JOBW_JOB_PID
JOBW_EXIT_CODE=$?
#JOBW_EXIT_CODE=${PIPESTATUS[0]}
#JOBW_EXIT_CODE=${PIPESTATUS[$(( (${#PIPESTATUS[@]} - 2 ) ))]}

for job in `jobs -p`; do
    wait $job
done


JOBW_END_SEC=`date "+%s"`
JOBW_DURATION_SEC="$(( ($JOBW_END_SEC - $JOBW_START_SEC) ))"
if [ $JOBW_IS_DARWIN -gt 0 ]; then
    JOBW_END_DATE="`date -jf '%s' $JOBW_END_SEC`"
else
    JOBW_END_DATE="`date -d@$JOBW_END_SEC`"
fi
JOBW_DURATION_DATE=$(show_time $JOBW_DURATION_SEC)

JOBW_EXIT_STAT="`$SCRIPT_DIR/interp_exit_code $JOBW_EXIT_CODE`"
JOBW_ABS="$JOBW_ABS"$'PID:\t'"$JOBW_JOB_PID"$'\n'
JOBW_ABS="$JOBW_ABS"$'Exit code:\t'"$JOBW_EXIT_CODE"$'\t('"$JOBW_EXIT_STAT"$')\n'
JOBW_ABS="$JOBW_ABS"$'Start:\t'"$JOBW_START_DATE"$'\n'
JOBW_ABS="$JOBW_ABS"$'End:\t'"$JOBW_END_DATE"$'\n'
JOBW_ABS="$JOBW_ABS"$'Duration:\t'"$JOBW_DURATION_DATE"' ( '"$JOBW_DURATION_SEC"' sec )'$'\n'
if [ ! -z "$JOBW_LOG_FILE" ]; then
    JOBW_LOG_FILE_ABS_PATH=`echo "$(cd "$(dirname "$JOBW_LOG_FILE")"; pwd)/$(basename "$JOBW_LOG_FILE")"`
    JOBW_ABS="$JOBW_ABS"$'Log:\t'"$JOBW_LOG_FILE_ABS_PATH"
    if [ "$JOBW_OVERWRITE" -gt "0" ]; then
        JOBW_ABS="$JOBW_ABS"$'\n'
    else
        JOBW_ABS="$JOBW_ABS"$'\t'"(Appended)"$'\n'
    fi
fi
if [ ! -z "$JOBW_MORE" ]; then
    JOBW_ABS="$JOBW_ABS"$'\n'"More: "$'\n*--------------\n'"$JOBW_MORE"$'\n*--------------\n'
fi
if [ "$JOBW_LINES" -gt "0" ]; then
    JOBW_ABS="$JOBW_ABS"$'\n'"Abstract: "$'\n*--------------\n'"`cat $JOBW_TMP_FILE.abs_txt`"$'\n*--------------\n'
fi

if [ ! -z "$JOBW_LOG_FILE" ]; then
    echo "$JOBW_ABS" >> $JOBW_LOG_FILE
fi

echo
echo "======== JOBW: SUMMARY ======"

echo "$JOBW_ABS"

if [ ! -z "$JOBW_EMAIL" ]; then
    if [ "$JOBW_LOG_IN_EMAIL" -gt "0" ]; then
        { echo "$JOBW_ABS" ; cat $JOBW_TMP_FILE.log_txt ; } > $JOBW_TMP_FILE.abs_full &
    else
        echo "$JOBW_ABS"  > $JOBW_TMP_FILE.abs_full &
    fi
    cat $JOBW_TMP_FILE.abs_full | mail -s "[$JOBW_SUBJECT] $JOBW_CMD" "$JOBW_EMAIL"
    echo "EMAIL TO :    $JOBW_EMAIL"
fi



rm -f $JOBW_TMP_FILE.*

}

function safe_int_force() {
    echo "................... [FORCE KILLING JOB - PID: "$JOBW_JOB_PID"]"
    kill -9 $JOBW_JOB_PID
}

function safe_int() {
    echo "................... [TRY TO KILL JOB - PID: "$JOBW_JOB_PID"]"
    kill -15 $JOBW_JOB_PID
    trap safe_int_force 2
    
    finish
    exit $JOBW_EXIT_CODE
}

function safe_hup() {
    finish
    exit $JOBW_EXIT_CODE
}

function show_time () {
    num=$1
    min=0
    hour=0
    day=0
    if((num>59));then
        ((sec=num%60))
        ((num=num/60))
        if((num>59));then
            ((min=num%60))
            ((num=num/60))
            if((num>23));then
                ((hour=num%24))
                ((day=num/24))
            else
                ((hour=num))
            fi
        else
            ((min=num))
        fi
    else
        ((sec=num))
    fi
    echo "$day"d "$hour"h "$min"m "$sec"s
}

# main

set -o ignoreeof

trap 'safe_hup' 1
trap 'exit 130' 2  # 2 is for Ctrl+C

JOBW_VERSION="scm-1"

if [ -z "$JOBW_SUBJECT" ]; then
    JOBW_SUBJECT='jobw'
fi
JOBW_OVERWRITE=0
if [ -z "$JOBW_LOG_BYTE" ]; then
    JOBW_LOG_BYTE='5120'
fi
if [ -z "$JOBW_LINES" ]; then
    JOBW_LINES='10'
fi
if [ -z "$JOBW_LOG_IN_EMAIL" ]; then
    JOBW_LOG_IN_EMAIL=1
fi

if [ -z "$JOBW_INTERRUPTIBLE" ]; then
    JOBW_INTERRUPTIBLE=0
fi

JOBW_INTERACT=1

JOBW_SHOW_HELP=0

while getopts "a:YNus:o:wnb:c:fl:m:Iivh" opt; do
case $opt in
  v)
      echo "JOBW: version:" $JOBW_VERSION
      exit 0
      ;;
  h)
      JOBW_SHOW_HELP=1
      ;;
  a)    # email to the spefic address
      JOBW_EMAIL="$OPTARG"
      ;;
  Y)
      JOBW_LOG_IN_EMAIL=1
      ;;
  N)
      JOBW_LOG_IN_EMAIL=0
      ;;
  u)    # do not send email
      unset JOBW_EMAIL
      ;;
  s)
      JOBW_SUBJECT="$OPTARG"
      ;;
  o)
      JOBW_LOG_FILE="$OPTARG"
      ;;
  w)
      JOBW_OVERWRITE=1
      ;;
  n)
      unset JOBW_LOG_FILE
      ;;
  b)
      JOBW_LOG_BYTE=`expr "$OPTARG" "*" "512"`
      if [ -z "$JOBW_LOG_BYTE" ]; then 
          echo "wrong arg for -b" >&2; exit
      fi
      ;;
  c)
      JOBW_LOG_BYTE=`expr "$OPTARG" "+" "0"`
      if [ -z "$JOBW_LOG_BYTE" ]; then 
          echo "wrong arg for -c" >&2; exit
      fi
      ;;
  f)
      JOBW_LOG_BYTE='inf'
      ;;
  l)
      JOBW_LINES=`expr "$OPTARG" "+" "0"`
      if [ -z "$JOBW_LINES" ]; then 
          echo "wrong arg for -l" >&2; exit
      fi
      ;;
  I)
      JOBW_INTERRUPTIBLE=1
      ;;
  i)
      JOBW_INTERRUPTIBLE=0
      ;;
  m)
      JOBW_MORE="$OPTARG"
      ;;
  d)
      JOBW_INTERACT=0
      ;;
  \?)
    echo "Invalid option: $OPTARG" >&2
    exit 1
    ;;
esac
done 
#\
#if read line ; then
#    echo "$line" >&2
#    cat >&2
#    exit 1 
#fi

shift $((OPTIND-1))
[ "$1" = "--" ] && shift

if [ -z "$1" ]; then
    JOBW_SHOW_HELP=1
fi

if [ "$JOBW_SHOW_HELP" -gt 0 ]; then
    show_help
    exit
fi

# end of parameter parsing

pushd `dirname $0` > /dev/null ; SCRIPT_DIR="`pwd`"; popd > /dev/null

JOBW_IS_DARWIN="`uname -a | grep Darwin`"
if [ -z "$JOBW_IS_DARWIN" ]; then
    JOBW_IS_DARWIN=0
    MD5SUM='md5sum'
else
    JOBW_IS_DARWIN=1
    MD5SUM='md5'
fi
JOBW_START_SEC=`date +"%s"`
if [ $JOBW_IS_DARWIN -gt 0 ]; then
    JOBW_START_DATE="`date -jf '%s' $JOBW_START_SEC`"
else
    JOBW_START_DATE="`date -d@$JOBW_START_SEC`"
fi

# ========================================
JOBW_CMD=""
# store arguments in a special array 
args=("$@") 
# get number of elements 
ELEMENTS=${#args[@]} 
 
# echo each element in array  
# for loop 
for (( i=0;i<$ELEMENTS;i++)); do 
   arg_i="${args[${i}]}";
   arg_i_str=`printf '%q ' "$arg_i"`
   JOBW_CMD="$JOBW_CMD$arg_i_str"
done
JOBW_CMD="${JOBW_CMD:0:$(( (${#JOBW_CMD} - 1) ))}"
# ========================================

JOBW_ABS=$'Subject:\t'"$JOBW_SUBJECT"$'\n'
JOBW_ABS="${JOBW_ABS}`"$SCRIPT_DIR/session_info"`"$'\n'
JOBW_ABS="$JOBW_ABS"$'CMD:\t'"$JOBW_CMD"$'\n'

mkdir -p /tmp/jobw-`whoami`
JOBW_TMP_FILE="/tmp/jobw-`whoami`/""`echo $JOBW_ABS | $MD5SUM | awk '{print $1}'`".$JOBW_START_SEC.$$

echo $JOBW_TMP_FILE

mkfifo $JOBW_TMP_FILE.log
mkfifo $JOBW_TMP_FILE.log_trunc
mkfifo $JOBW_TMP_FILE.abs
mkfifo $JOBW_TMP_FILE.abs_full
mkfifo $JOBW_TMP_FILE.stdout


if [ ! -z "$JOBW_LOG_FILE" ]; then
    if [ "$JOBW_OVERWRITE" -gt "0" ]; then
        printf '' > "$JOBW_LOG_FILE" 
    fi
    echo $'\n'"***************************** JOBW: NEW ENTRY ***************************"$'\n' >> $JOBW_LOG_FILE
    { echo "======== JOBW: BEGIN OF LOG ======"$'\n'; \
        cat $JOBW_TMP_FILE.log_trunc ; \
        echo "======== JOBW: END OF LOG ======"$'\n';  \
        } | tee -a $JOBW_LOG_FILE > $JOBW_TMP_FILE.log_txt &
else
    { echo "======== JOBW: BEGIN OF LOG ======"$'\n'; \
        cat $JOBW_TMP_FILE.log_trunc ; \
        echo "======== JOBW: END OF LOG ======"$'\n'; \
        } > $JOBW_TMP_FILE.log_txt &
fi

if [ "$JOBW_LOG_BYTE" = "inf" ]; then
    cat < $JOBW_TMP_FILE.log > $JOBW_TMP_FILE.log_trunc &
else
    { head -c$JOBW_LOG_BYTE; \
        { tail -c$JOBW_LOG_BYTE | { \
        if read line; then \
            echo $'\n\n''======== JOBW: MIDDLE OF LOG ======'$'\n'; \
            echo "$line"; \
            cat; \
        fi; } \
        } ; } \
        < $JOBW_TMP_FILE.log > $JOBW_TMP_FILE.log_trunc &
fi

tail -n$JOBW_LINES $JOBW_TMP_FILE.abs > $JOBW_TMP_FILE.abs_txt &

if [ "$JOBW_INTERRUPTIBLE" -eq "0" ]; then
    trap safe_int 2
    # 2 is for Ctrl+C
else
    trap 'exit 130' 2  # 2 is for Ctrl+C
fi

#"$SCRIPT_DIR/run_as_is"
"$@" > $JOBW_TMP_FILE.stdout 2>&1 & echo $! > $JOBW_TMP_FILE.pid 
JOBW_JOB_PID=`cat $JOBW_TMP_FILE.pid`
( cat $JOBW_TMP_FILE.stdout | tee $JOBW_TMP_FILE.log $JOBW_TMP_FILE.abs ) &
$SCRIPT_DIR/jjobw_guard $$ $JOBW_JOB_PID &
while kill -0 $JOBW_JOB_PID > /dev/null ; do
    if [ "$JOBW_INTERACT" -eq "0" ]; then
        sleep 1
        continue;
    fi
    if read JOBW_INTER_CMD ; then
        :
    else
        echo "...................  [CTRL+D]" >&2
        echo "           [ 'term' to quit ]"
        #echo "...................  [SIGKILL]" >&2
        #kill -9 $JOBW_JOB_PID
    fi
    JOBW_INTER_CMD1=`echo $JOBW_INTER_CMD`
    if [ "$JOBW_INTER_CMD1" == "" ]; then
        :
    elif [ "$JOBW_INTER_CMD" == "int" ]; then
        echo "...................  [SIGINT]" >&2
        kill -2 $JOBW_JOB_PID
    elif [ "$JOBW_INTER_CMD" == "hup" ]; then
        echo "...................  [SIGHUP]" >&2
        kill -1 $JOBW_JOB_PID
    elif [ "$JOBW_INTER_CMD" == "term" ]; then
        echo "...................  [SIGTERM]" >&2
        kill -15 $JOBW_JOB_PID
    elif [ "$JOBW_INTER_CMD" == "kill" ]; then
        echo "...................  [SIGKILL]" >&2
        kill -9 $JOBW_JOB_PID
    elif [ "$JOBW_INTER_CMD" == "quit" ]; then
        echo "...................  [SIGQUIT]" >&2
        kill -3 $JOBW_JOB_PID
    elif [ "${JOBW_INTER_CMD:0:3}" == "sig" ]; then
        JOBW_SIG_NUM=`echo "${JOBW_INTER_CMD:3}"`
        echo "...................  [SIG $JOBW_SIG_NUM]" >&2
        kill -$JOBW_SIG_NUM $JOBW_JOB_PID
    elif [ "${JOBW_INTER_CMD:0:5}" == "email" ]; then
        JOBW_EMAIL=`echo ${JOBW_INTER_CMD:5}`
        echo "...................  [EMAIL $JOBW_EMAIL]"
    elif [ "$JOBW_INTER_CMD" == "pwd" ]; then
        echo "...................  [PWD]" >&2
        echo "[PWD] `pwd`"
    elif [ "$JOBW_INTER_CMD" == "bash" ]; then
        echo "...................  [BASH START]" >&2
        bash
        echo "...................  [BASH END]" >&2
    else
        echo "...................  [UNKNOWN COMMAND]" >&2
    fi
done

finish

